In [1]:
import pandas as pd
import numpy as np

In [2]:
votes = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/countypres_2000-2024.csv")
unemployment = pd.read_excel("https://raw.github.com/jamilditter/election_results/refs/heads/main/data/LAUS_Annual_Unemployment_By_State_2000to2024.xlsx", skiprows=3)
med_income = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/Median_Household_Income_By_State_FRED.csv")
age = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/State_by_Age.csv")
education = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/State_Education_by_Degree.csv")
population = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/Population%20by%20Age%20and%20Sex%20-%20US%2C%20States%2C%20Counties.csv")
bach_2024 = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/FRED_BachelorsEduAttainment2024.csv")
alaska_med_income = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/MEHOINUSAKA646N.csv")
rhode_is_med_income = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/MEHOINUSRIA672N_new.csv")
voter_participation = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/voter_participation.csv")

In [3]:
votes["totalvotes"] = votes.groupby(["state", "year"])["candidatevotes"].transform("sum")
votes["dem"] = votes[votes["party"] == "DEMOCRAT"].groupby(["state", "year"])["candidatevotes"].transform("sum")
votes["rep"] = votes[votes["party"] == "REPUBLICAN"].groupby(["state", "year"])["candidatevotes"].transform("sum")

totalvotes_melted = pd.melt(
    votes, id_vars = ["state", "year"],
    value_vars = ["totalvotes"],
    var_name = "party",
    value_name = "total_votes"
).drop_duplicates().dropna().drop(columns=["party"])

demvotes_melted = pd.melt(
    votes, id_vars = ["state", "year"],
    value_vars = ["dem"],
    var_name = "party",
    value_name = "dem_votes"
).drop_duplicates().dropna().drop(columns=["party"])

repvotes_melted = pd.melt(
    votes, id_vars = ["state", "year"],
    value_vars = ["rep"],
    var_name = "party",
    value_name = "rep_votes"
).drop_duplicates().dropna().drop(columns=["party"])

In [4]:
rename_states = {
    'LAUST010000000000003': 'Alabama',
    'LAUST020000000000003': 'Alaska',
    'LAUST040000000000003': 'Arizona',
    'LAUST050000000000003': 'Arkansas',
    'LAUST060000000000003': 'California',
    'LAUST080000000000003': 'Colorado',
    'LAUST090000000000003': 'Connecticut',
    'LAUST100000000000003': 'Delaware',
    'LAUST110000000000003': 'District of Columbia',
    'LAUST120000000000003': 'Florida',
    'LAUST130000000000003': 'Georgia',
    'LAUST150000000000003': 'Hawaii',
    'LAUST160000000000003': 'Idaho',
    'LAUST170000000000003': 'Illinois',
    'LAUST180000000000003': 'Indiana',
    'LAUST190000000000003': 'Iowa',
    'LAUST200000000000003': 'Kansas',
    'LAUST210000000000003': 'Kentucky',
    'LAUST220000000000003': 'Louisiana',
    'LAUST230000000000003': 'Maine',
    'LAUST240000000000003': 'Maryland',
    'LAUST250000000000003': 'Massachusetts',
    'LAUST260000000000003': 'Michigan',
    'LAUST270000000000003': 'Minnesota',
    'LAUST280000000000003': 'Mississippi',
    'LAUST290000000000003': 'Missouri',
    'LAUST300000000000003': 'Montana',
    'LAUST310000000000003': 'Nebraska',
    'LAUST320000000000003': 'Nevada',
    'LAUST330000000000003': 'New Hampshire',
    'LAUST340000000000003': 'New Jersey',
    'LAUST350000000000003': 'New Mexico',
    'LAUST360000000000003': 'New York',
    'LAUST370000000000003': 'North Carolina',
    'LAUST380000000000003': 'North Dakota',
    'LAUST390000000000003': 'Ohio',
    'LAUST400000000000003': 'Oklahoma',
    'LAUST410000000000003': 'Oregon',
    'LAUST420000000000003': 'Pennsylvania',
    'LAUST440000000000003': 'Rhode Island',
    'LAUST450000000000003': 'South Carolina',
    'LAUST460000000000003': 'South Dakota',
    'LAUST470000000000003': 'Tennessee',
    'LAUST480000000000003': 'Texas',
    'LAUST490000000000003': 'Utah',
    'LAUST500000000000003': 'Vermont',
    'LAUST510000000000003': 'Virginia',
    'LAUST530000000000003': 'Washington',
    'LAUST540000000000003': 'West Virginia',
    'LAUST550000000000003': 'Wisconsin',
    'LAUST560000000000003': 'Wyoming'
}

unemployment["Series ID"] = unemployment["Series ID"].replace(rename_states)

In [5]:
unemployment_renamed = unemployment.rename(columns = lambda x: x[-4:]).rename(columns={"s ID": "state"})

In [6]:
unemployment_melted = pd.melt(
    unemployment_renamed, id_vars = ["state"],
    value_vars = ["2000", "2004", "2008", "2012", "2016", "2020", "2024"],
    var_name = "year",
    value_name = "unemployment_rate"
)

election_years = ["2000", "2004", "2008", "2012", "2016", "2020", "2024"]
unemployment_melted = unemployment_melted[unemployment_melted["year"].isin(election_years)]
unemployment_melted["year"].unique()

array(['2000', '2004', '2008', '2012', '2016', '2020', '2024'],
      dtype=object)

In [7]:
abbr_to_state = {
    "ALA": "Alabama",
    "AKA": "Alaska",
    "ARA": "Arkansas",
    "AZA": "Arizona",
    "CAA": "California",
    "COA": "Colorado",
    "CTA": "Connecticut",
    "DCA": "District of Columbia",
    "DEA": "Delaware",
    "FLA": "Florida",
    "GAA": "Georgia",
    "HIA": "Hawaii",
    "IDA": "Idaho",
    "ILA": "Illinois",
    "INA": "Indiana",
    "IAA": "Iowa",
    "KSA": "Kansas",
    "KYA": "Kentucky",
    "LAA": "Louisiana", 
    "MEA": "Maine",
    "MDA": "Maryland",
    "MAA": "Massachusetts",
    "MIA": "Michigan",
    "MNA": "Minnesota",
    "MSA": "Mississippi",
    "MOA": "Missouri",
    "MTA": "Montana",
    "NEA": "Nebraska",
    "NVA": "Nevada",
    "NHA": "New Hampshire",
    "NJA": "New Jersey",
    "NMA": "New Mexico",
    "NYA": "New York",
    "NCA": "North Carolina",
    "NDA": "North Dakota",
    "OHA": "Ohio",
    "OKA": "Oklahoma",
    "ORA": "Oregon",
    "PAA": "Pennsylvania",
    "RIA": "Rhode Island",
    "SCA": "South Carolina",
    "SDA": "South Dakota",
    "TNA": "Tennessee",
    "TXA": "Texas",
    "UTA": "Utah",
    "VAA": "Virginia",
    "VTA": "Vermont",
    "WAA": "Washington",
    "WIA": "Wisconsin",
    "WVA": "West Virginia",
    "WYA": "Wyoming"
}

med_income["observation_date"] = pd.to_datetime(med_income["observation_date"]).dt.year

c:\jamil\Temp\ipykernel_40596\4086705710.py:55: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  med_income["observation_date"] = pd.to_datetime(med_income["observation_date"]).dt.year

In [8]:
alaska_med_income["observation_date"] = pd.to_datetime(alaska_med_income["observation_date"]).dt.year

In [9]:
rhode_is_med_income["observation_date"] = pd.to_datetime(rhode_is_med_income["observation_date"]).dt.year

In [10]:
med_income_merged = pd.merge(alaska_med_income, med_income)
med_income_merged = pd.merge(rhode_is_med_income, med_income_merged)

In [11]:
med_income_renamed = med_income_merged.rename(columns={"observation_date": "year"})

In [12]:
med_income_melted = pd.melt(
    med_income_renamed, id_vars = ["year"],
    value_vars = ['MEHOINUSALA672N', 'MEHOINUSAKA646N', 'MEHOINUSARA672N', 'MEHOINUSAZA672N', 'MEHOINUSCAA672N', 
                  'MEHOINUSCOA672N', 'MEHOINUSCTA672N', 'MEHOINUSDCA672N', 'MEHOINUSDEA672N', 'MEHOINUSFLA672N', 
                  'MEHOINUSGAA672N', 'MEHOINUSHIA672N', 'MEHOINUSIAA672N', 'MEHOINUSIDA672N', 'MEHOINUSILA672N', 
                  'MEHOINUSINA672N', 'MEHOINUSKSA672N', 'MEHOINUSKYA672N', 'MEHOINUSLAA672N', 'MEHOINUSMAA672N', 
                  'MEHOINUSMDA672N', 'MEHOINUSMEA672N', 'MEHOINUSMIA672N', 'MEHOINUSMNA672N', 'MEHOINUSMOA672N', 
                  'MEHOINUSMSA672N', 'MEHOINUSMTA672N', 'MEHOINUSNEA672N', 'MEHOINUSNCA672N', 'MEHOINUSNDA672N', 
                  'MEHOINUSNHA672N', 'MEHOINUSNJA672N', 'MEHOINUSNMA672N', 'MEHOINUSNVA672N', 'MEHOINUSNYA672N', 
                  'MEHOINUSOHA672N', 'MEHOINUSOKA672N', 'MEHOINUSORA672N', 'MEHOINUSPAA672N', 'MEHOINUSSCA672N', 
                  'MEHOINUSSDA672N', 'MEHOINUSTNA672N', 'MEHOINUSTXA672N', 'MEHOINUSUTA672N', 'MEHOINUSVAA672N', 
                  'MEHOINUSVTA672N', 'MEHOINUSWAA672N', 'MEHOINUSWIA672N', 'MEHOINUSWVA672N', 'MEHOINUSWYA672N',
                  'MEHOINUSRIA672N'],
    var_name = "state",
    value_name = "median_income"
)

med_income_melted["state"] = med_income_melted["state"].str[8:11].map(abbr_to_state)
med_income_melted["year"] = med_income_melted["year"].astype(str)

med_income_melted = med_income_melted[med_income_melted["year"].isin(election_years)]
med_income_melted["year"].unique()

array(['2000', '2004', '2008', '2012', '2016', '2020', '2024'],
      dtype=object)

In [13]:
fips_to_states = {
    1: "Alabama",
    2: "Alaska",
    4: "Arizona",
    5: "Arkansas",
    6: "California",
    8: "Colorado",
    9: "Connecticut",
    10: "Delaware",
    11: "District of Columbia",
    12: "Florida",
    13: "Georgia",
    15: "Hawaii",
    16: "Idaho",
    17: "Illinois",
    18: "Indiana",
    19: "Iowa",
    20: "Kansas",
    21: "Kentucky",
    22: "Louisiana",
    23: "Maine",
    24: "Maryland",
    25: "Massachusetts",
    26: "Michigan",
    27: "Minnesota",
    28: "Mississippi",
    29: "Missouri",
    30: "Montana",
    31: "Nebraska",
    32: "Nevada",
    33: "New Hampshire",
    34: "New Jersey",
    35: "New Mexico",
    36: "New York",
    37: "North Carolina",
    38: "North Dakota",
    39: "Ohio",
    40: "Oklahoma",
    41: "Oregon",
    42: "Pennsylvania",
    44: "Rhode Island",
    45: "South Carolina",
    46: "South Dakota",
    47: "Tennessee",
    48: "Texas",
    49: "Utah",
    50: "Vermont",
    51: "Virginia",
    53: "Washington",
    54: "West Virginia",
    55: "Wisconsin",
    56: "Wyoming"
}

age["STATEFIP"] = age["STATEFIP"].replace(fips_to_states)

In [14]:
age = age.rename(columns = {"STATEFIP": "state", "YEAR": "year"})

med_age = age.loc[:, ["state", "year", "med_age"]]

In [15]:
education.head()

,STATEFIP,YEAR,total_pop,bach_pop,hs_pop,assoc_pop,masters_pop,drs_pop
0,1,2000,1531294,366846,834824,162140,145153,22331
1,1,2004,1668813,398768,884667,198097,161298,25983
2,1,2008,1799699,420962,979366,204430,169564,25377
3,1,2012,893318,450959,0,227969,185956,28434
4,1,2016,989675,487746,0,260917,208372,32640

In [16]:
education["STATEFIP"] = education["STATEFIP"].replace(fips_to_states)
education = education.rename(columns = {"STATEFIP": "state", "YEAR": "year"})

In [17]:
education["bach_per"] = education["bach_pop"] / education["total_pop"]
education["hs_per"] = education["hs_pop"] / education["total_pop"]

bach_2024["year"] = 2024
bach_2024 = bach_2024.rename(columns = {"State": "state"})

In [18]:
bach_2024["2024 Bachelors or Higher"] = bach_2024["2024 Bachelors or Higher"]/100

In [19]:
education_merge = pd.merge(education, bach_2024, on=["state", "year"], how="outer")
education_merge.loc[education_merge["year"] == 2024, "bach_per"] = education_merge.loc[education_merge["year"] == 2024, "2024 Bachelors or Higher"]
education_merge = education_merge.drop(columns = ["2024 Bachelors or Higher"])

In [20]:
edu_bach = education_merge.loc[:, ["state", "year", "bach_per"]]

In [21]:
population.tail(50
                )

,IBRC_Geo_ID,Statefips,Countyfips,Description,Year,Total Population,Population 0-4,Population 5-17,Population 18-24,Population 25-44,Population 45-64,Population 65+,Population Under 18,Population 18-54,Population 55+,Male Population,Female Population
79852,56043,56,43,"Washakie County, WY",2007,8169,538,1484,570,1825,2363,1389,2022,3659,2488.0,4084,4085
79853,56043,56,43,"Washakie County, WY",2008,8229,555,1480,558,1826,2410,1400,2035,3655,2539.0,4094,4135
79854,56043,56,43,"Washakie County, WY",2009,8423,571,1533,533,1921,2416,1449,2104,3714,2605.0,4197,4226
79855,56043,56,43,"Washakie County, WY",2010,8531,593,1580,515,1894,2440,1509,2173,3658,2700.0,4252,4279
79856,56043,56,43,"Washakie County, WY",2011,8451,545,1598,509,1842,2427,1530,2143,3566,2742.0,4246,4205
79857,56043,56,43,"Washakie County, WY",2012,8410,512,1609,532,1833,2368,1556,2121,3544,2745.0,4221,4189
79858,56043,56,43,"Washakie County, WY",2013,8417,508,1564,561,1851,2330,1603,2072,3521,2824.0,4217,4200
79859,56043,56,43,"Washakie County, WY",2014,8277,485,1522,547,1821,2258,1644,2007,3418,2852.0,4164,4113
79860,56043,56,43,"Washakie County, WY",2015,8282,495,1512,564,1837,2223,1651,2007,3426,2849.0,4192,4090
79861,56043,56,43,"Washakie County, WY",2016,8180,471,1517,542,1816,2159,1675,1988,3340,2852.0,4126,4054
79862,56043,56,43,"Washakie County, WY",2017,8013,421,1472,528,1756,2157,1679,1893,3263,2857.0,4050,3963
79863,56043,56,43,"Washakie County, WY",2018,7886,403,1392,530,1707,2130,1724,1795,3208,2883.0,3983,3903
79864,56043,56,43,"Washakie County, WY",2019,7824,394,1388,516,1727,2038,1761,1782,3151,2891.0,3971,3853
79865,56043,56,43,"Washakie County, WY",2020,7663,385,1333,503,1693,2013,1736,1718,3083,2858.0,3941,3722
79866,56043,56,43,"Washakie County, WY",2021,7727,367,1269,531,1711,2034,1815,1636,3151,2934.0,3976,3751
79867,56043,56,43,"Washakie County, WY",2022,7728,366,1238,532,1727,2009,1856,1604,3159,2958.0,3994,3734
79868,56043,56,43,"Washakie County, WY",2023,7736,350,1226,530,1724,2001,1905,1576,3171,2969.0,3995,3741
79869,56043,56,43,"Washakie County, WY",2024,7662,349,1172,524,1683,1963,1971,1521,3119,NaN,3998,3664
79870,56045,56,45,"Weston County, WY",2000,6627,348,1244,487,1735,1773,1042,1590,3283,1754.0,3361,3266
79871,56045,56,45,"Weston County, WY",2001,6487,350,1162,511,1600,1820,1058,1498,3216,1773.0,3321,3166
79872,56045,56,45,"Weston County, WY",2002,6578,357,1150,550,1597,1875,1056,1500,3256,1822.0,3364,3214
79873,56045,56,45,"Weston County, WY",2003,6610,330,1128,598,1565,1934,1060,1453,3300,1857.0,3413,3197
79874,56045,56,45,"Weston County, WY",2004,6646,331,1123,598,1551,1966,1080,1451,3278,1917.0,3434,3212
79875,56045,56,45,"Weston County, WY",2005,6594,326,1072,599,1504,2004,1089,1398,3265,1931.0,3421,3173
79876,56045,56,45,"Weston County, WY",2006,6717,350,1066,597,1483,2107,1112,1418,3284,2015.0,3496,3221
79877,56045,56,45,"Weston County, WY",2007,7033,373,1108,610,1625,2193,1127,1478,3477,2078.0,3688,3345
79878,56045,56,45,"Weston County, WY",2008,7133,395,1106,597,1717,2207,1114,1498,3529,2106.0,3737,3396
79879,56045,56,45,"Weston County, WY",2009,7266,410,1152,611,1750,2215,1133,1557,3555,2154.0,3820,3446
79880,56045,56,45,"Weston County, WY",2010,7198,410,1164,532,1705,2230,1157,1574,3397,2227.0,3786,3412
79881,56045,56,45,"Weston County, WY",2011,7142,410,1160,509,1718,2176,1169,1570,3312,2260.0,3768,3374
79882,56045,56,45,"Weston County, WY",2012,7075,408,1128,519,1679,2133,1208,1536,3230,2309.0,3732,3343
79883,56045,56,45,"Weston County, WY",2013,7132,447,1106,533,1700,2138,1208,1553,3222,2357.0,3759,3373
79884,56045,56,45,"Weston County, WY",2014,7134,427,1117,532,1691,2118,1249,1544,3200,2390.0,3766,3368
79885,56045,56,45,"Weston County, WY",2015,7202,440,1114,552,1706,2123,1267,1554,3188,2460.0,3796,3406
79886,56045,56,45,"Weston County, WY",2016,7228,448,1122,528,1727,2108,1295,1570,3155,2503.0,3794,3434
79887,56045,56,45,"Weston County, WY",2017,6962,373,1057,460,1683,2032,1357,1430,2980,2552.0,3665,3297
79888,56045,56,45,"Weston County, WY",2018,6895,351,1088,415,1675,1957,1409,1439,2900,2556.0,3624,3271
79889,56045,56,45,"Weston County, WY",2019,6880,333,1072,425,1662,1914,1474,1405,2863,2612.0,3615,3265
79890,72000,72,0,Puerto Rico,2010,3721525,222319,674705,375882,972221,929514,546884,897024,1835708,983762.0,1782782,1938743
79891,72000,72,0,Puerto Rico,2010,3721525,222319,674705,375882,972221,929514,546884,897024,1835708,983762.0,1785370,1940787
79892,72000,72,0,Puerto Rico,2010,3721525,222319,674705,375882,972221,929514,546884,897024,1835708,983762.0,1785171,1940618
79893,72000,72,0,Puerto Rico,2011,3678732,213461,653157,374648,949922,924300,563244,866618,1808560,1003554.0,1763441,1915291
79894,72000,72,0,Puerto Rico,2012,3634488,204487,630969,372223,930003,915727,581079,835456,1780253,1018779.0,1739072,1895416
79895,72000,72,0,Puerto Rico,2013,3593077,195598,608709,368701,913334,907625,599110,804307,1753893,1034877.0,1720280,1872797
79896,72000,72,0,Puerto Rico,2014,3534874,184490,584203,360590,892653,898289,614649,768693,1717264,1048917.0,1688886,1845988
79897,72000,72,0,Puerto Rico,2015,3473232,172208,559788,348790,873430,889620,629396,731996,1678391,1062845.0,1656361,1816871
79898,72000,72,0,Puerto Rico,2016,3406672,160089,533468,336650,851966,881072,643427,693557,1637171,1075944.0,1620266,1786406
79899,72000,72,0,Puerto Rico,2017,3325284,144751,506785,322684,827174,869104,654786,651536,1588500,1085248.0,1580779,1744505
79900,72000,72,0,Puerto Rico,2018,3193344,124490,467385,304190,787275,848601,661403,591875,1513778,1087691.0,1517003,1676341
79901,72000,72,0,Puerto Rico,2019,3193553,117561,455240,303279,793537,844387,679549,572801,1512839,1107913.0,1515598,1677955

In [22]:
population_renamed = population.rename(columns = {"Total Population": "total_pop", "Year": "year", "Description": "state"})
population_renamed["voting_age_pop"] = population_renamed["Population 18-54"] + population_renamed["Population 55+"]
population_renamed = population_renamed.loc[:, ["state", "year", "voting_age_pop", "Population 18-24", "Population 25-44", "Population 45-64", "Population 65+"]]
population_renamed = population_renamed.loc[population_renamed["state"] != "U.S."]
population_renamed["year"] = population_renamed["year"].astype(str)
population_renamed = population_renamed[population_renamed["year"].isin(election_years)]

In [23]:
voter_participation.head()

        State  2024  2020  2016  2012  2008  2004  2000
0     Alabama  58.7  60.5  57.4  61.9  62.4  63.2  60.4
1      Alaska  62.1  63.8  61.3  58.4  65.0  67.6  67.7
2     Arizona  61.7  71.9  60.4  55.9  59.9  63.8  52.5
3    Arkansas  52.8  54.0  58.7  53.3  53.8  58.7  50.5
4  California  64.7  65.1  57.9  57.5  63.4  61.9  57.9

In [24]:
voter_participation_melt = pd.melt(voter_participation,
                                   id_vars="State",
                                   value_vars=["2000", "2004", "2008", "2012", "2016", "2020", "2024"],
                                    var_name = "year",
                                    value_name="voter_participation").iloc[:-6].rename(columns = {"State": "state"})

In [25]:
unemployment_melted["year"] = unemployment_melted["year"].astype(int)
unemployment_melted["state"] = unemployment_melted["state"].str.upper()
med_income_melted["year"] = med_income_melted["year"].astype(int)
med_income_melted["state"] = med_income_melted["state"].str.upper()
med_age["state"] = med_age["state"].str.upper()
edu_bach["state"] = edu_bach["state"].str.upper()
population_renamed["state"] = population_renamed["state"].str.upper()
population_renamed["year"] = population_renamed["year"].astype(int)
voter_participation_melt["year"] = voter_participation_melt["year"].astype(int)
voter_participation_melt["state"] = voter_participation_melt["state"].str.upper()

merge1 = pd.merge(totalvotes_melted, demvotes_melted, on=["state", "year"], how="left")
merge2 = pd.merge(merge1, repvotes_melted, on=["state", "year"], how="left")
merge3 = pd.merge(merge2, unemployment_melted, on=["state", "year"], how="left")
merge4 = pd.merge(merge3, med_income_melted, on=["state", "year"], how="left")
merge5 = pd.merge(merge4, med_age, on=["state", "year"], how="left")
merge6 = pd.merge(merge5, edu_bach, on=["state", "year"], how="left")
merge7 = pd.merge(merge6, voter_participation_melt, on=["state", "year"], how="left")
merged_data = pd.merge(merge7, population_renamed, on=["state", "year"], how="left")

merged_data["dem_votes_per"] = merged_data["dem_votes"] / merged_data["total_votes"]
merged_data["rep_votes_per"] = merged_data["rep_votes"] / merged_data["total_votes"]

merged_data["dem_win"] = merged_data["dem_votes_per"] > merged_data["rep_votes_per"]

In [26]:
import os

save_path = "/Users/jamil/Coding/election_results/data/Voting_Breakdown_By_Socioeconomic_and_Demographic_Factors.csv"

os.makedirs(os.path.dirname(save_path), exist_ok=True)

merged_data.to_csv(save_path, index=False)

In [27]:
merged_data.isna().sum().to_frame(name='Number of Missing Values')

                     Number of Missing Values
state                                       0
year                                        0
total_votes                                 0
dem_votes                                   0
rep_votes                                   0
unemployment_rate                           0
median_income                               0
med_age                                    51
bach_per                                    0
voter_participation                         0
voting_age_pop                              0
Population 18-24                            0
Population 25-44                            0
Population 45-64                            0
Population 65+                              0
dem_votes_per                               0
rep_votes_per                               0
dem_win                                     0