In [1]:
import pandas as pd
import numpy as np

In [2]:
votes = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/countypres_2000-2024.csv")
unemployment = pd.read_excel("https://raw.github.com/jamilditter/election_results/refs/heads/main/data/LAUS_Annual_Unemployment_By_State_2000to2024.xlsx", skiprows=3)
med_income = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/Median_Household_Income_By_State_FRED.csv")
age = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/State_by_Age.csv")
education = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/State_Education_by_Degree.csv")
population = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/Population%20by%20Age%20and%20Sex%20-%20US%2C%20States%2C%20Counties.csv")
bach_2024 = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/FRED_BachelorsEduAttainment2024.csv")
alaska_med_income = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/MEHOINUSAKA646N.csv")
rhode_is_med_income = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/MEHOINUSRIA672N_new.csv")
voter_participation = pd.read_csv("https://raw.githubusercontent.com/jamilditter/election_results/refs/heads/main/data/voter_participation.csv")

In [3]:
votes["totalvotes"] = votes.groupby(["state", "year"])["candidatevotes"].transform("sum")
votes["dem"] = votes[votes["party"] == "DEMOCRAT"].groupby(["state", "year"])["candidatevotes"].transform("sum")
votes["rep"] = votes[votes["party"] == "REPUBLICAN"].groupby(["state", "year"])["candidatevotes"].transform("sum")

totalvotes_melted = pd.melt(
    votes, id_vars = ["state", "year"],
    value_vars = ["totalvotes"],
    var_name = "party",
    value_name = "total_votes"
).drop_duplicates().dropna().drop(columns=["party"])

demvotes_melted = pd.melt(
    votes, id_vars = ["state", "year"],
    value_vars = ["dem"],
    var_name = "party",
    value_name = "dem_votes"
).drop_duplicates().dropna().drop(columns=["party"])

repvotes_melted = pd.melt(
    votes, id_vars = ["state", "year"],
    value_vars = ["rep"],
    var_name = "party",
    value_name = "rep_votes"
).drop_duplicates().dropna().drop(columns=["party"])

In [4]:
rename_states = {
    'LAUST010000000000003': 'Alabama',
    'LAUST020000000000003': 'Alaska',
    'LAUST040000000000003': 'Arizona',
    'LAUST050000000000003': 'Arkansas',
    'LAUST060000000000003': 'California',
    'LAUST080000000000003': 'Colorado',
    'LAUST090000000000003': 'Connecticut',
    'LAUST100000000000003': 'Delaware',
    'LAUST110000000000003': 'District of Columbia',
    'LAUST120000000000003': 'Florida',
    'LAUST130000000000003': 'Georgia',
    'LAUST150000000000003': 'Hawaii',
    'LAUST160000000000003': 'Idaho',
    'LAUST170000000000003': 'Illinois',
    'LAUST180000000000003': 'Indiana',
    'LAUST190000000000003': 'Iowa',
    'LAUST200000000000003': 'Kansas',
    'LAUST210000000000003': 'Kentucky',
    'LAUST220000000000003': 'Louisiana',
    'LAUST230000000000003': 'Maine',
    'LAUST240000000000003': 'Maryland',
    'LAUST250000000000003': 'Massachusetts',
    'LAUST260000000000003': 'Michigan',
    'LAUST270000000000003': 'Minnesota',
    'LAUST280000000000003': 'Mississippi',
    'LAUST290000000000003': 'Missouri',
    'LAUST300000000000003': 'Montana',
    'LAUST310000000000003': 'Nebraska',
    'LAUST320000000000003': 'Nevada',
    'LAUST330000000000003': 'New Hampshire',
    'LAUST340000000000003': 'New Jersey',
    'LAUST350000000000003': 'New Mexico',
    'LAUST360000000000003': 'New York',
    'LAUST370000000000003': 'North Carolina',
    'LAUST380000000000003': 'North Dakota',
    'LAUST390000000000003': 'Ohio',
    'LAUST400000000000003': 'Oklahoma',
    'LAUST410000000000003': 'Oregon',
    'LAUST420000000000003': 'Pennsylvania',
    'LAUST440000000000003': 'Rhode Island',
    'LAUST450000000000003': 'South Carolina',
    'LAUST460000000000003': 'South Dakota',
    'LAUST470000000000003': 'Tennessee',
    'LAUST480000000000003': 'Texas',
    'LAUST490000000000003': 'Utah',
    'LAUST500000000000003': 'Vermont',
    'LAUST510000000000003': 'Virginia',
    'LAUST530000000000003': 'Washington',
    'LAUST540000000000003': 'West Virginia',
    'LAUST550000000000003': 'Wisconsin',
    'LAUST560000000000003': 'Wyoming'
}

unemployment["Series ID"] = unemployment["Series ID"].replace(rename_states)

In [5]:
unemployment_renamed = unemployment.rename(columns = lambda x: x[-4:]).rename(columns={"s ID": "state"})

In [6]:
unemployment_melted = pd.melt(
    unemployment_renamed, id_vars = ["state"],
    value_vars = ["2000", "2004", "2008", "2012", "2016", "2020", "2024"],
    var_name = "year",
    value_name = "unemployment_rate"
)

election_years = ["2000", "2004", "2008", "2012", "2016", "2020", "2024"]
unemployment_melted = unemployment_melted[unemployment_melted["year"].isin(election_years)]
unemployment_melted["year"].unique()

array(['2000', '2004', '2008', '2012', '2016', '2020', '2024'],
      dtype=object)

In [7]:
abbr_to_state = {
    "ALA": "Alabama",
    "AKA": "Alaska",
    "ARA": "Arkansas",
    "AZA": "Arizona",
    "CAA": "California",
    "COA": "Colorado",
    "CTA": "Connecticut",
    "DCA": "District of Columbia",
    "DEA": "Delaware",
    "FLA": "Florida",
    "GAA": "Georgia",
    "HIA": "Hawaii",
    "IDA": "Idaho",
    "ILA": "Illinois",
    "INA": "Indiana",
    "IAA": "Iowa",
    "KSA": "Kansas",
    "KYA": "Kentucky",
    "LAA": "Louisiana", 
    "MEA": "Maine",
    "MDA": "Maryland",
    "MAA": "Massachusetts",
    "MIA": "Michigan",
    "MNA": "Minnesota",
    "MSA": "Mississippi",
    "MOA": "Missouri",
    "MTA": "Montana",
    "NEA": "Nebraska",
    "NVA": "Nevada",
    "NHA": "New Hampshire",
    "NJA": "New Jersey",
    "NMA": "New Mexico",
    "NYA": "New York",
    "NCA": "North Carolina",
    "NDA": "North Dakota",
    "OHA": "Ohio",
    "OKA": "Oklahoma",
    "ORA": "Oregon",
    "PAA": "Pennsylvania",
    "RIA": "Rhode Island",
    "SCA": "South Carolina",
    "SDA": "South Dakota",
    "TNA": "Tennessee",
    "TXA": "Texas",
    "UTA": "Utah",
    "VAA": "Virginia",
    "VTA": "Vermont",
    "WAA": "Washington",
    "WIA": "Wisconsin",
    "WVA": "West Virginia",
    "WYA": "Wyoming"
}

med_income["observation_date"] = pd.to_datetime(med_income["observation_date"]).dt.year

c:\jamil\Temp\ipykernel_38392\4086705710.py:55: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  med_income["observation_date"] = pd.to_datetime(med_income["observation_date"]).dt.year

In [8]:
alaska_med_income["observation_date"] = pd.to_datetime(alaska_med_income["observation_date"]).dt.year

In [9]:
rhode_is_med_income["observation_date"] = pd.to_datetime(rhode_is_med_income["observation_date"]).dt.year

In [10]:
med_income_merged = pd.merge(alaska_med_income, med_income)
med_income_merged = pd.merge(rhode_is_med_income, med_income_merged)

In [11]:
med_income_renamed = med_income_merged.rename(columns={"observation_date": "year"})

In [12]:
med_income_melted = pd.melt(
    med_income_renamed, id_vars = ["year"],
    value_vars = ['MEHOINUSALA672N', 'MEHOINUSAKA646N', 'MEHOINUSARA672N', 'MEHOINUSAZA672N', 'MEHOINUSCAA672N', 
                  'MEHOINUSCOA672N', 'MEHOINUSCTA672N', 'MEHOINUSDCA672N', 'MEHOINUSDEA672N', 'MEHOINUSFLA672N', 
                  'MEHOINUSGAA672N', 'MEHOINUSHIA672N', 'MEHOINUSIAA672N', 'MEHOINUSIDA672N', 'MEHOINUSILA672N', 
                  'MEHOINUSINA672N', 'MEHOINUSKSA672N', 'MEHOINUSKYA672N', 'MEHOINUSLAA672N', 'MEHOINUSMAA672N', 
                  'MEHOINUSMDA672N', 'MEHOINUSMEA672N', 'MEHOINUSMIA672N', 'MEHOINUSMNA672N', 'MEHOINUSMOA672N', 
                  'MEHOINUSMSA672N', 'MEHOINUSMTA672N', 'MEHOINUSNEA672N', 'MEHOINUSNCA672N', 'MEHOINUSNDA672N', 
                  'MEHOINUSNHA672N', 'MEHOINUSNJA672N', 'MEHOINUSNMA672N', 'MEHOINUSNVA672N', 'MEHOINUSNYA672N', 
                  'MEHOINUSOHA672N', 'MEHOINUSOKA672N', 'MEHOINUSORA672N', 'MEHOINUSPAA672N', 'MEHOINUSSCA672N', 
                  'MEHOINUSSDA672N', 'MEHOINUSTNA672N', 'MEHOINUSTXA672N', 'MEHOINUSUTA672N', 'MEHOINUSVAA672N', 
                  'MEHOINUSVTA672N', 'MEHOINUSWAA672N', 'MEHOINUSWIA672N', 'MEHOINUSWVA672N', 'MEHOINUSWYA672N',
                  'MEHOINUSRIA672N'],
    var_name = "state",
    value_name = "median_income"
)

med_income_melted["state"] = med_income_melted["state"].str[8:11].map(abbr_to_state)
med_income_melted["year"] = med_income_melted["year"].astype(str)

med_income_melted = med_income_melted[med_income_melted["year"].isin(election_years)]
med_income_melted["year"].unique()

array(['2000', '2004', '2008', '2012', '2016', '2020', '2024'],
      dtype=object)

In [13]:
fips_to_states = {
    1: "Alabama",
    2: "Alaska",
    4: "Arizona",
    5: "Arkansas",
    6: "California",
    8: "Colorado",
    9: "Connecticut",
    10: "Delaware",
    11: "District of Columbia",
    12: "Florida",
    13: "Georgia",
    15: "Hawaii",
    16: "Idaho",
    17: "Illinois",
    18: "Indiana",
    19: "Iowa",
    20: "Kansas",
    21: "Kentucky",
    22: "Louisiana",
    23: "Maine",
    24: "Maryland",
    25: "Massachusetts",
    26: "Michigan",
    27: "Minnesota",
    28: "Mississippi",
    29: "Missouri",
    30: "Montana",
    31: "Nebraska",
    32: "Nevada",
    33: "New Hampshire",
    34: "New Jersey",
    35: "New Mexico",
    36: "New York",
    37: "North Carolina",
    38: "North Dakota",
    39: "Ohio",
    40: "Oklahoma",
    41: "Oregon",
    42: "Pennsylvania",
    44: "Rhode Island",
    45: "South Carolina",
    46: "South Dakota",
    47: "Tennessee",
    48: "Texas",
    49: "Utah",
    50: "Vermont",
    51: "Virginia",
    53: "Washington",
    54: "West Virginia",
    55: "Wisconsin",
    56: "Wyoming"
}

age["STATEFIP"] = age["STATEFIP"].replace(fips_to_states)

In [14]:
age = age.rename(columns = {"STATEFIP": "state", "YEAR": "year"})

med_age = age.loc[:, ["state", "year", "med_age"]]

In [15]:
education.head()

,STATEFIP,YEAR,total_pop,bach_pop,hs_pop,assoc_pop,masters_pop,drs_pop
0,1,2000,1531294,366846,834824,162140,145153,22331
1,1,2004,1668813,398768,884667,198097,161298,25983
2,1,2008,1799699,420962,979366,204430,169564,25377
3,1,2012,893318,450959,0,227969,185956,28434
4,1,2016,989675,487746,0,260917,208372,32640

In [16]:
education["STATEFIP"] = education["STATEFIP"].replace(fips_to_states)
education = education.rename(columns = {"STATEFIP": "state", "YEAR": "year"})

In [17]:
education["bach_per"] = education["bach_pop"] / education["total_pop"]
education["hs_per"] = education["hs_pop"] / education["total_pop"]

bach_2024["year"] = 2024
bach_2024 = bach_2024.rename(columns = {"State": "state"})

In [18]:
bach_2024["2024 Bachelors or Higher"] = bach_2024["2024 Bachelors or Higher"]/100

In [19]:
education_merge = pd.merge(education, bach_2024, on=["state", "year"], how="outer")
education_merge.loc[education_merge["year"] == 2024, "bach_per"] = education_merge.loc[education_merge["year"] == 2024, "2024 Bachelors or Higher"]
education_merge = education_merge.drop(columns = ["2024 Bachelors or Higher"])

In [ ]:
edu_bach = education_merge.loc[:, ["state", "year", "bach_per"]]

In [21]:
population_renamed = population.rename(columns = {"Total Population": "total_pop", "Year": "year", "Description": "state"})
population_renamed = population_renamed.loc[:, ["state", "year", "Population 18-24", "Population 25-44", "Population 45-64", "Population 65+"]]
population_renamed = population_renamed.loc[population_renamed["state"] != "U.S."]
population_renamed["year"] = population_renamed["year"].astype(str)
population_renamed = population_renamed[population_renamed["year"].isin(election_years)]

population_renamed.head()

,state,year,Population 18-24,Population 25-44,Population 45-64,Population 65+
25,Alabama,2000,442244,1284371,1022405,580880
29,Alabama,2004,457934,1231571,1133736,593826
33,Alabama,2008,470431,1231410,1244494,636944
37,Alabama,2012,485538,1225621,1290419,698085
41,Alabama,2016,462098,1231213,1289047,784005

In [22]:
voter_participation.head()

        State  2024  2020  2016  2012  2008  2004  2000
0     Alabama  58.7  60.5  57.4  61.9  62.4  63.2  60.4
1      Alaska  62.1  63.8  61.3  58.4  65.0  67.6  67.7
2     Arizona  61.7  71.9  60.4  55.9  59.9  63.8  52.5
3    Arkansas  52.8  54.0  58.7  53.3  53.8  58.7  50.5
4  California  64.7  65.1  57.9  57.5  63.4  61.9  57.9

In [23]:
voter_participation_melt = pd.melt(voter_participation,
                                   id_vars="State",
                                   value_vars=["2000", "2004", "2008", "2012", "2016", "2020", "2024"],
                                    var_name = "year",
                                    value_name="voter_participation").iloc[:-6].rename(columns = {"State": "state"})

In [ ]:
unemployment_melted["year"] = unemployment_melted["year"].astype(int)
unemployment_melted["state"] = unemployment_melted["state"].str.upper()
med_income_melted["year"] = med_income_melted["year"].astype(int)
med_income_melted["state"] = med_income_melted["state"].str.upper()
med_age["state"] = med_age["state"].str.upper()
edu_bach["state"] = edu_bach["state"].str.upper()
population_renamed["state"] = population_renamed["state"].str.upper()
population_renamed["year"] = population_renamed["year"].astype(int)
voter_participation_melt["year"] = voter_participation_melt["year"].astype(int)
voter_participation_melt["state"] = voter_participation_melt["state"].str.upper()

merge1 = pd.merge(totalvotes_melted, demvotes_melted, on=["state", "year"], how="left")
merge2 = pd.merge(merge1, repvotes_melted, on=["state", "year"], how="left")
merge3 = pd.merge(merge2, unemployment_melted, on=["state", "year"], how="left")
merge4 = pd.merge(merge3, med_income_melted, on=["state", "year"], how="left")
merge5 = pd.merge(merge4, med_age, on=["state", "year"], how="left")
merge6 = pd.merge(merge5, edu_bach, on=["state", "year"], how="left")
merge7 = pd.merge(merge6, voter_participation_melt, on=["state", "year"], how="left")
merged_data = pd.merge(merge7, population_renamed, on=["state", "year"], how="left")

merged_data["dem_votes_per"] = merged_data["dem_votes"] / merged_data["total_votes"]
merged_data["rep_votes_per"] = merged_data["rep_votes"] / merged_data["total_votes"]

merged_data["dem_win"] = merged_data["dem_votes_per"] > merged_data["rep_votes_per"]

merged_data["bach_per"].tail(100)

257    0.504558
258    0.506929
259    0.539876
260    0.545784
261    0.497595
         ...
352    0.433000
353    0.410000
354    0.244000
355    0.346000
356    0.323000
Name: bach_per, Length: 100, dtype: float64

In [25]:
import os

save_path = "/Users/jamil/Coding/election_results/data/Voting_Breakdown_By_Socioeconomic_and_Demographic_Factors.csv"

os.makedirs(os.path.dirname(save_path), exist_ok=True)

merged_data.to_csv(save_path, index=False)

In [35]:
merged_data[merged_data["year"]==2008]

,state,year,total_votes,dem_votes,rep_votes,unemployment_rate,median_income,med_age,bach_per,hs_per,voter_participation,Population 18-24,Population 25-44,Population 45-64,Population 65+,dem_votes_per,rep_votes_per,dem_win
102,ALABAMA,2008,2099819,813479.0,1266546.0,5.9,62350,46.0,0.233907,0.544183,62.4,470431,1231410,1244494,636944,0.387404,0.603169,False
103,ALASKA,2008,326197,123594.0,193841.0,6.5,63990,44.0,0.270077,0.468968,65.0,75206,189673,189130,50322,0.378894,0.594245,False
104,ARIZONA,2008,2293475,1034707.0,1230111.0,5.8,65770,45.0,0.280655,0.451786,59.9,621451,1690369,1507727,832164,0.451153,0.536352,False
105,ARKANSAS,2008,1086617,422310.0,638017.0,5.4,55500,46.0,0.213494,0.603189,53.8,278835,745354,737074,407566,0.388647,0.587159,False
106,CALIFORNIA,2008,13561900,8274473.0,5011781.0,7.3,79930,43.0,0.329502,0.390401,63.4,3812579,10505976,8907401,4056760,0.610126,0.369549,True
107,COLORADO,2008,2401361,1288576.0,1073589.0,4.8,85440,44.0,0.350757,0.371660,68.4,481504,1404254,1286548,514135,0.536602,0.447075,True
108,CONNECTICUT,2008,1647085,1000291.0,628041.0,5.6,90680,46.0,0.290790,0.422288,67.2,320268,923555,982536,492594,0.607310,0.381305,True
109,DELAWARE,2008,412412,255459.0,152374.0,4.8,71080,46.0,0.247348,0.501425,67.3,88587,230357,235098,123716,0.619427,0.369470,True
110,DISTRICT OF COLUMBIA,2008,265853,245800.0,17367.0,6.5,77930,40.0,0.323421,0.328561,74.1,81763,192899,136532,66785,0.924571,0.065326,True
111,FLORIDA,2008,8391639,4282366.0,4046212.0,6.3,62890,47.0,0.265613,0.490405,63.8,1717154,4764109,4892666,3135004,0.510313,0.482172,True
112,GEORGIA,2008,3925278,1844137.0,2048744.0,6.4,64810,43.0,0.283458,0.487805,64.2,948921,2758599,2345888,972338,0.469811,0.521936,False
113,HAWAII,2008,452742,325201.0,120429.0,4.1,86250,45.0,0.289520,0.447638,51.8,128537,358796,359325,184461,0.718292,0.265999,True
114,IDAHO,2008,655032,236440.0,403012.0,5.0,66480,45.0,0.276312,0.481583,61.4,155327,396766,376702,183178,0.360959,0.615255,False
115,ILLINOIS,2008,5523051,3419673.0,2031527.0,6.5,74660,44.0,0.292679,0.450446,62.6,1245766,3537433,3240921,1569517,0.619164,0.367827,True
116,INDIANA,2008,2751054,1374039.0,1345648.0,5.9,65220,46.0,0.222474,0.562240,60.5,643543,1690585,1661552,817632,0.499459,0.489139,True
117,IOWA,2008,1536820,828940.0,682379.0,4.1,70300,47.0,0.250601,0.523831,70.2,307267,746335,790684,446790,0.539387,0.444020,True
118,KANSAS,2008,1235872,514765.0,699655.0,4.6,67120,46.0,0.300727,0.457880,63.3,292316,717210,716536,367325,0.416520,0.566123,False
119,KENTUCKY,2008,1826508,751985.0,1048462.0,6.5,57690,45.0,0.200638,0.584498,63.1,407552,1152941,1146722,560662,0.411706,0.574025,False
120,LOUISIANA,2008,1959085,781574.0,1148015.0,4.7,55460,45.0,0.232362,0.599454,70.3,469138,1169750,1150107,537863,0.398948,0.585996,False
121,MAINE,2008,731163,421923.0,295273.0,5.4,66210,48.0,0.240932,0.523170,71.2,117246,326952,400769,203338,0.577057,0.403840,True
122,MARYLAND,2008,2631596,1629467.0,959862.0,4.3,89320,45.0,0.299080,0.409069,68.3,543624,1569212,1534657,678258,0.619193,0.364745,True
123,MASSACHUSETTS,2008,3081336,1904103.0,1108885.0,5.3,84560,45.0,0.310772,0.392145,67.1,661626,1754618,1745822,877174,0.617947,0.359871,True
124,MICHIGAN,2008,5001766,2872579.0,2048639.0,8.2,69800,46.0,0.244085,0.508028,67.8,970359,2537217,2699413,1321021,0.574313,0.409583,True
125,MINNESOTA,2008,2910369,1573354.0,1275409.0,5.4,77000,45.0,0.316252,0.421468,75.0,512238,1405692,1386084,658825,0.540603,0.438229,True
126,MISSISSIPPI,2008,1285259,554662.0,724497.0,6.7,51090,44.0,0.220513,0.552262,69.7,304997,767502,744419,370316,0.431557,0.563697,False
127,MISSOURI,2008,2925205,1441911.0,1445814.0,6.1,64540,46.0,0.250374,0.528528,65.8,586722,1532837,1563077,812335,0.492926,0.494261,False
128,MONTANA,2008,496072,232156.0,243860.0,4.7,60140,48.0,0.284884,0.498517,65.4,97094,233215,281961,140331,0.467989,0.491582,False
129,NEBRASKA,2008,801281,333319.0,452979.0,3.2,71120,46.0,0.285366,0.473538,67.3,184622,459084,458137,240748,0.415983,0.565319,False
130,NEVADA,2008,967848,533736.0,412827.0,6.9,76750,45.0,0.248682,0.529546,59.9,244687,774847,668457,303018,0.551467,0.426541,True
131,NEW HAMPSHIRE,2008,710970,384826.0,316534.0,3.8,92770,46.0,0.297677,0.435618,71.2,122815,335808,389896,171358,0.541269,0.445214,True
132,NEW JERSEY,2008,3838498,2215422.0,1613207.0,5.4,91550,45.0,0.311423,0.445753,64.1,751070,2389516,2336233,1157905,0.577159,0.420270,True
133,NEW MEXICO,2008,830158,472422.0,346832.0,4.4,59020,46.0,0.245236,0.475779,62.6,201729,508578,530767,258374,0.569075,0.417790,True
134,NEW YORK,2008,7591233,4769700.0,2742298.0,5.4,70740,45.0,0.273783,0.439665,58.8,1936825,5324739,5019433,2559269,0.628317,0.361245,True
135,NORTH CAROLINA,2008,4310789,2142651.0,2128474.0,5.9,60180,45.0,0.280044,0.472599,67.5,910643,2570907,2405101,1170697,0.497044,0.493755,True
136,NORTH DAKOTA,2008,316621,141278.0,168601.0,3.0,69580,45.0,0.299518,0.444247,67.5,82307,159328,172687,95785,0.446205,0.532501,False
137,OHIO,2008,5698048,2933388.0,2674491.0,6.6,65800,46.0,0.230431,0.551751,65.5,1089460,2959430,3108404,1589129,0.514806,0.469370,True
138,OKLAHOMA,2008,1462661,502496.0,960165.0,3.6,64640,46.0,0.247228,0.544078,58.7,378846,949236,940042,490235,0.343549,0.656451,False
139,OREGON,2008,1827864,1037291.0,738475.0,6.3,72520,46.0,0.293104,0.439607,67.6,356879,1012559,1025602,508044,0.567488,0.404010,True
140,PENNSYLVANIA,2008,5977981,3266523.0,2649934.0,5.4,72060,47.0,0.231334,0.550078,62.4,1231877,3173801,3456191,1929412,0.546426,0.443282,True
141,RHODE ISLAND,2008,471766,296571.0,165391.0,7.6,74640,45.0,0.286434,0.452112,67.4,118410,272611,284482,149702,0.628640,0.350578,True
142,SOUTH CAROLINA,2008,1920969,862449.0,1034896.0,6.9,59100,45.0,0.244949,0.514136,65.6,462550,1196665,1198687,596978,0.448966,0.538736,False
143,SOUTH DAKOTA,2008,377708,170924.0,203054.0,3.1,72340,47.0,0.259770,0.517028,67.8,82232,195036,208133,113875,0.452529,0.537595,False
144,TENNESSEE,2008,2600124,1087437.0,1479178.0,6.5,55660,45.0,0.241304,0.558436,55.5,589192,1691716,1655153,816996,0.418225,0.568887,False
145,TEXAS,2008,8077795,3528633.0,4479328.0,4.9,65180,43.0,0.299599,0.469989,56.1,2511528,6921332,5736274,2463988,0.436831,0.554524,False
146,UTAH,2008,952370,327670.0,596030.0,3.3,87670,40.0,0.313635,0.413404,53.1,319576,746850,524154,235191,0.344057,0.625839,False
147,VERMONT,2008,325046,219262.0,98974.0,4.5,71090,48.0,0.283457,0.449026,64.7,65116,151259,187934,87242,0.674557,0.304492,True
148,VIRGINIA,2008,3723260,1959532.0,1725005.0,4.1,86900,44.0,0.306789,0.413459,68.7,792590,2189453,2082718,930374,0.526295,0.463305,True
149,WASHINGTON,2008,3036878,1750848.0,1229216.0,5.2,79390,45.0,0.314457,0.397552,66.8,642409,1819408,1762619,777493,0.576529,0.404763,True
150,WEST VIRGINIA,2008,713451,303857.0,397466.0,4.5,53260,47.0,0.163500,0.657439,53.4,166170,463268,528748,291914,0.425898,0.557103,False
151,WISCONSIN,2008,2983417,1677211.0,1262393.0,4.9,71780,46.0,0.252159,0.509582,71.2,555711,1462682,1521168,755862,0.562178,0.423137,True
152,WYOMING,2008,256035,82868.0,164958.0,3.0,74770,46.0,0.240224,0.503575,64.3,56979,138230,152645,66678,0.323659,0.644279,False

In [27]:
merged_data.isna().sum().to_frame(name='Number of Missing Values')

                     Number of Missing Values
state                                       0
year                                        0
total_votes                                 0
dem_votes                                   0
rep_votes                                   0
unemployment_rate                           0
median_income                               0
med_age                                    51
bach_per                                    0
hs_per                                     51
voter_participation                         0
Population 18-24                            0
Population 25-44                            0
Population 45-64                            0
Population 65+                              0
dem_votes_per                               0
rep_votes_per                               0
dem_win                                     0

In [28]:
merged_data[merged_data.isna().any(axis=1)]

,state,year,total_votes,dem_votes,rep_votes,unemployment_rate,median_income,med_age,bach_per,hs_per,voter_participation,Population 18-24,Population 25-44,Population 45-64,Population 65+,dem_votes_per,rep_votes_per,dem_win
306,ALABAMA,2024,2264972,772412.0,1462616.0,3.1,65560,NaN,0.299,NaN,58.7,488175,1309411,1269355,955901,0.341025,0.645755,False
307,ALASKA,2024,338177,140026.0,184458.0,4.6,91260,NaN,0.328,NaN,62.1,67634,221499,166847,109206,0.414061,0.545448,False
308,ARIZONA,2024,4693783,2145165.0,2461122.0,3.6,84700,NaN,0.347,NaN,61.7,727663,2029372,1748722,1488452,0.457023,0.524337,False
309,ARKANSAS,2024,2365352,793810.0,1518482.0,3.5,64840,NaN,0.271,NaN,52.8,289139,797605,736924,562842,0.335599,0.641969,False
310,CALIFORNIA,2024,15862678,9276179.0,6081697.0,5.3,100600,NaN,0.381,NaN,64.7,3651201,11304902,9534735,6521873,0.584780,0.383397,True
311,COLORADO,2024,3190873,1728159.0,1377441.0,4.3,106500,NaN,0.478,NaN,70.1,551003,1825340,1392084,975901,0.541594,0.431682,True
312,CONNECTICUT,2024,1759010,992053.0,736918.0,3.2,99240,NaN,0.426,NaN,66.3,347520,942048,943471,714203,0.563984,0.418939,True
313,DELAWARE,2024,511697,289758.0,214351.0,3.7,85860,NaN,0.360,NaN,69.8,89979,260488,258709,229028,0.566269,0.418902,True
314,DISTRICT OF COLUMBIA,2024,328414,294185.0,21076.0,5.2,104800,NaN,0.655,NaN,79.5,70089,272451,138920,90959,0.895775,0.064175,True
315,FLORIDA,2024,10893752,4683038.0,6110125.0,3.4,75630,NaN,0.358,NaN,60.3,1901378,5993139,5886744,5091262,0.429883,0.560883,False
316,GEORGIA,2024,5250047,2548017.0,2663117.0,3.5,81210,NaN,0.363,NaN,64.4,1063702,3050106,2765978,1760341,0.485332,0.507256,False
317,HAWAII,2024,516701,313044.0,193661.0,3.0,98240,NaN,0.378,NaN,58.5,116860,381606,344007,310324,0.605851,0.374803,True
318,IDAHO,2024,905057,274972.0,605246.0,3.7,81650,NaN,0.330,NaN,65.2,199067,523380,456318,354407,0.303817,0.668738,False
319,ILLINOIS,2024,5633310,3062863.0,2449079.0,5.0,84210,NaN,0.392,NaN,65.9,1175497,3439308,3126594,2271298,0.543706,0.434750,True
320,INDIANA,2024,2936677,1163603.0,1720347.0,4.2,76710,NaN,0.307,NaN,60.7,672597,1795399,1656283,1213910,0.396231,0.585814,False
321,IOWA,2024,3347301,1413835.0,1854038.0,3.0,85480,NaN,0.321,NaN,71.8,327279,817261,753994,612379,0.422381,0.553890,False
322,KANSAS,2024,1327591,544853.0,758802.0,3.6,87690,NaN,0.360,NaN,70.7,306571,768814,674465,528177,0.410407,0.571563,False
323,KENTUCKY,2024,2074530,704043.0,1337494.0,5.1,64790,NaN,0.279,NaN,67.7,418240,1184972,1132793,826695,0.339375,0.644721,False
324,LOUISIANA,2024,2974974,1133303.0,1799142.0,4.4,60740,NaN,0.278,NaN,58.0,423036,1212754,1081029,814527,0.380946,0.604759,False
325,MAINE,2024,824806,430342.0,376991.0,3.1,90730,NaN,0.371,NaN,67.1,112833,346624,368208,330265,0.521749,0.457066,True
326,MARYLAND,2024,3038334,1902577.0,1035550.0,3.0,109700,NaN,0.447,NaN,71.1,535704,1673990,1580289,1102000,0.626191,0.340828,True
327,MASSACHUSETTS,2024,3473668,2126518.0,1251303.0,4.0,113900,NaN,0.483,NaN,68.9,710415,1951360,1781743,1336934,0.612182,0.360225,True
328,MICHIGAN,2024,5664186,2736533.0,2816636.0,4.7,79460,NaN,0.333,NaN,72.3,937461,2597136,2510596,1985923,0.483129,0.497271,False
329,MINNESOTA,2024,3253920,1656979.0,1519032.0,3.0,92350,NaN,0.400,NaN,75.9,517817,1539910,1379220,1057147,0.509225,0.466831,True
330,MISSISSIPPI,2024,1228008,466668.0,747744.0,3.2,55980,NaN,0.270,NaN,68.9,286671,739982,712983,528787,0.380020,0.608908,False
331,MISSOURI,2024,2995327,1200599.0,1751986.0,3.7,78390,NaN,0.335,NaN,69.5,571880,1632548,1499363,1169583,0.400824,0.584906,False
332,MONTANA,2024,602963,231906.0,352079.0,3.0,81920,NaN,0.363,NaN,69.2,102571,296749,265907,239351,0.384611,0.583915,False
333,NEBRASKA,2024,947159,369995.0,564816.0,2.8,86140,NaN,0.354,NaN,67.4,201031,521381,449292,349449,0.390637,0.596326,False
334,NEVADA,2024,1484840,705197.0,751205.0,5.6,80590,NaN,0.285,NaN,66.9,261935,934830,806300,575966,0.474931,0.505916,False
335,NEW HAMPSHIRE,2024,826189,418488.0,395523.0,2.6,111800,NaN,0.415,NaN,71.9,119795,359471,377058,303344,0.506528,0.478732,True
336,NEW JERSEY,2024,4272725,2220713.0,1968215.0,4.5,103500,NaN,0.445,NaN,72.5,804545,2509330,2435891,1706102,0.519742,0.460646,True
337,NEW MEXICO,2024,920922,478802.0,423391.0,4.1,64140,NaN,0.318,NaN,66.0,204285,557952,490535,429581,0.519916,0.459747,True
338,NEW YORK,2024,8262495,4619195.0,3578899.0,4.3,86830,NaN,0.412,NaN,59.2,1788344,5409303,4932770,3754552,0.559056,0.433150,True
339,NORTH CAROLINA,2024,5699141,2715375.0,2898423.0,3.6,67220,NaN,0.371,NaN,64.6,1051378,2921820,2738455,1974069,0.476453,0.508572,False
340,NORTH DAKOTA,2024,368155,112327.0,246505.0,2.4,88080,NaN,0.340,NaN,71.2,90723,216881,165937,137764,0.305108,0.669569,False
341,OHIO,2024,5767788,2533699.0,3180116.0,4.3,80520,NaN,0.324,NaN,67.4,1058339,3090107,2890949,2269539,0.439284,0.551358,False
342,OKLAHOMA,2024,3132346,999198.0,2072426.0,3.3,65310,NaN,0.293,NaN,59.7,404558,1098672,934066,691883,0.318993,0.661621,False
343,OREGON,2024,2244493,1240600.0,919480.0,4.2,89700,NaN,0.378,NaN,75.3,366720,1200066,1028566,850804,0.552731,0.409660,True
344,PENNSYLVANIA,2024,14068412,6846084.0,7086616.0,3.6,80060,NaN,0.364,NaN,69.7,1185695,3370876,3226427,2665932,0.486628,0.503725,False
345,RHODE ISLAND,2024,511816,283750.0,214291.0,4.3,92290,NaN,0.390,NaN,70.0,111508,300429,277181,218599,0.554398,0.418688,True
346,SOUTH CAROLINA,2024,7644420,2056904.0,2967494.0,4.1,76780,NaN,0.333,NaN,62.7,499753,1395738,1354324,1076945,0.269073,0.388191,False
347,SOUTH DAKOTA,2024,428922,146859.0,272081.0,1.8,79850,NaN,0.342,NaN,58.9,86464,233363,210336,173800,0.342391,0.634337,False
348,TENNESSEE,2024,3063942,1056265.0,1966865.0,3.4,75860,NaN,0.324,NaN,64.8,647077,1935902,1784295,1277959,0.344741,0.641939,False
349,TEXAS,2024,50534517,8746992.0,11507322.0,4.1,81490,NaN,0.352,NaN,57.9,3072175,9000743,7189978,4362712,0.173089,0.227712,False
350,UTAH,2024,1488494,562566.0,883818.0,3.2,104000,NaN,0.391,NaN,66.9,417924,1004680,714307,433073,0.377943,0.593767,False
351,VERMONT,2024,669861,210938.0,108055.0,2.3,85260,NaN,0.451,NaN,71.7,63480,158949,165469,147621,0.314898,0.161310,True
352,VIRGINIA,2024,4482576,2335395.0,2075085.0,2.9,97720,NaN,0.433,NaN,72.9,814730,2391548,2174373,1547113,0.520994,0.462922,True
353,WASHINGTON,2024,3924243,2245849.0,1530923.0,4.5,97500,NaN,0.410,NaN,70.0,675175,2386166,1862213,1379589,0.572301,0.390119,True
354,WEST VIRGINIA,2024,1524780,214309.0,533556.0,4.1,63150,NaN,0.244,NaN,59.5,156303,425293,452573,387446,0.140551,0.349923,False
355,WISCONSIN,2024,6845836,1668229.0,1697626.0,3.0,82560,NaN,0.346,NaN,72.2,564553,1509688,1477002,1168733,0.243685,0.247979,False
356,WYOMING,2024,271123,69527.0,192633.0,3.2,78680,NaN,0.323,NaN,63.8,54709,151746,137503,115668,0.256441,0.710500,False

In [29]:
merged_data[merged_data["state"]=="RHODE ISLAND"]

,state,year,total_votes,dem_votes,rep_votes,unemployment_rate,median_income,med_age,bach_per,hs_per,voter_participation,Population 18-24,Population 25-44,Population 45-64,Population 65+,dem_votes_per,rep_votes_per,dem_win
39,RHODE ISLAND,2000,409112,249508.0,130555.0,4.0,72150,43.0,0.268708,0.467935,63.5,107167,310069,232537,152430,0.609877,0.319118,True
90,RHODE ISLAND,2004,436289,259760.0,169046.0,5.3,75650,45.0,0.267972,0.470030,63.7,115173,299215,264260,149703,0.595385,0.387463,True
141,RHODE ISLAND,2008,471766,296571.0,165391.0,7.6,74640,45.0,0.286434,0.452112,67.4,118410,272611,284482,149702,0.628640,0.350578,True
192,RHODE ISLAND,2012,446052,279677.0,157204.0,10.3,74070,46.0,0.504883,0.000000,62.5,121073,261914,295272,159101,0.627005,0.352434,True
243,RHODE ISLAND,2016,464144,252525.0,180543.0,5.2,78550,47.0,0.502798,0.000000,60.6,114468,267005,293603,173559,0.544066,0.388981,True
294,RHODE ISLAND,2020,517757,307486.0,199922.0,9.2,96170,48.0,0.513225,0.000000,66.3,111778,285126,293845,194071,0.593881,0.386131,True
345,RHODE ISLAND,2024,511816,283750.0,214291.0,4.3,92290,NaN,0.390000,NaN,70.0,111508,300429,277181,218599,0.554398,0.418688,True